"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, ArrowDown, ArrowUp, Code2, Braces, Layers3, Lightbulb, Send, LoaderCircle, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { TechBadge } from "@/components/tech-badge";
import { PersonalProjects } from "@/components/personal-projects";
const recipient="vincentius.clarishna@gmail.com";
const templates={
 freelance:{label:"Freelance project",subject:"Let’s discuss a freelance project",message:"Hi Vincentius,\n\nI’d love to collaborate with you on a freelance project.\n\nProject overview:\nScope and deliverables:\nPreferred timeline:\nBudget range:\n\nLet’s find a time to discuss the details. Thank you!"},
 remote:{label:"Full-time remote role",subject:"Full-time remote opportunity",message:"Hi Vincentius,\n\nWe’d like to discuss a full-time, fully remote opportunity with you.\n\nCompany and role:\nResponsibilities:\nTech stack:\nTime zone and working hours:\nCompensation range:\n\nWould you be available for an introductory conversation?"},
 hello:{label:"Just saying hello",subject:"Hello, Vincentius!",message:"Hi Vincentius,\n\nI came across your portfolio and wanted to connect.\n\nHere’s what I have in mind:\n\nLooking forward to hearing from you!"}
};
type Inquiry=keyof typeof templates;
const skills=[{icon:Braces,title:"Languages",description:"The foundations of the web.",tags:["JavaScript","TypeScript"]},{icon:Code2,title:"Frameworks & tooling",description:"From ideas to interactive interfaces.",tags:["Next.js","React","Vite"]},{icon:Layers3,title:"State management",description:"Keeping complex flows predictable.",tags:["Redux"]},{icon:Lightbulb,title:"Approach",description:"Breaking problems into clear solutions.",tags:["Problem solving"]}];
export default function Home(){
 const [active,setActive]=useState("home"),[kind,setKind]=useState<Inquiry>("freelance");
 const [drafts,setDrafts]=useState<Record<Inquiry,{subject:string;message:string}>>({...templates});
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[sending,setSending]=useState(false);
 const busy=useRef(false);
 const [feedback,setFeedback]=useState<{type:"success"|"error"|"notice";message:string}|null>(null);
 const draft=drafts[kind];
 const changeDraft=(key:"subject"|"message",value:string)=>{setDrafts(d=>({...d,[kind]:{...d[kind],[key]:value}}));setFeedback(null)};
 useEffect(()=>{
  const sections=Array.from(document.querySelectorAll<HTMLElement>("main section[id]"));
  const update=()=>{const current=[...sections].reverse().find(s=>s.getBoundingClientRect().top<=innerHeight*.4);setActive(innerHeight+scrollY>=document.documentElement.scrollHeight-8?"contact":current?.id??"home")};
  let frame=0;const onScroll=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update)};
  window.addEventListener("scroll",onScroll,{passive:true});update();
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("revealed");observer.unobserve(entry.target)}}),{threshold:.08});
  document.querySelectorAll(".reveal").forEach(el=>{el.classList.add("animate-ready");observer.observe(el)});
  return()=>{window.removeEventListener("scroll",onScroll);cancelAnimationFrame(frame);observer.disconnect()};
 },[]);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy.current)return;
  if(new FormData(event.currentTarget).get("website"))return;
  if(!name.trim()||!draft.message.trim()||!draft.subject.trim()){setFeedback({type:"error",message:"Please fill in your name, subject, and message."});return}
  busy.current=true;setSending(true);setFeedback(null);
  try{const response=await fetch(`https://formsubmit.co/ajax/${recipient}`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({name:name.trim(),email:email.trim(),inquiry:templates[kind].label,message:draft.message.trim(),_subject:draft.subject.trim(),_template:"table",_honey:""}),signal:AbortSignal.timeout(25000)});
   const result=await response.json() as {success?:boolean|string;message?:string};if(!response.ok||!(result.success===true||result.success==="true"))throw Error("send_failed");
   setFeedback(/activat|confirm.*email/i.test(String(result.message??""))?{type:"notice",message:"The email service is awaiting recipient activation. Please use the email link below to contact me directly."}:{type:"success",message:"Your message has been submitted. Thank you for reaching out!"});
  }catch{setFeedback({type:"error",message:"Your message could not be confirmed. Your draft is safe—please try again or open it in your email app below."})}finally{busy.current=false;setSending(false)}
 }
 const mailto=`mailto:${recipient}?subject=${encodeURIComponent(draft.subject)}&body=${encodeURIComponent(`${draft.message}\n\nFrom: ${name}\nEmail: ${email}`)}`;
 return <><a className="skip-link" href="#main">Skip to content</a><header className="header"><a className="wordmark" href="#home" aria-label="clrshna, home">clrshna<span aria-hidden="true">.</span></a><nav aria-label="Main navigation">{["Home","Work","Skill","Project","Contact"].map(item=><a key={item} className={active===item.toLowerCase()?"active":""} aria-current={active===item.toLowerCase()?"location":undefined} href={`#${item.toLowerCase()}`}>{item}</a>)}</nav><a className="nav-cta" href="#contact">Let’s talk <ArrowUpRight size={16}/></a></header>
 <main id="main"><section id="home" className="hero section"><div className="hero-top"><span className="eyebrow">FRONTEND DEVELOPER</span><span className="availability"><i/> Open for remote opportunities</span></div><div className="hero-grid"><div className="hero-intro"><p className="hero-greeting">Hi there, I’m</p><h1>Vincentius<br/><em>Clarishna.</em></h1><p className="hero-role">Frontend Developer</p><p className="hero-description">I’m enthusiastic about turning ideas into thoughtful, interactive web experiences. With JavaScript, TypeScript, and React, I love bringing interfaces to life—and learning something new with every build.</p><div className="hero-actions"><a className="primary-link" href="#work">Explore my work <ArrowDown size={18}/></a><a className="text-link" href="#contact">Let’s build something <ArrowUpRight size={18}/></a></div></div><figure className="hero-portrait"><img src="/images/vincentius-clarishna.png" alt="Illustrated portrait of Vincentius Clarishna at his frontend development workspace" width={1024} height={1024} fetchPriority="high"/><figcaption><span>VINCENTIUS CLARISHNA</span><span>Code. Create. Keep learning.</span></figcaption></figure></div><div className="hero-bottom"><span>AVAILABLE FOR FREELANCE & FULL-TIME WFH</span><span>SCROLL TO EXPLORE <ArrowDown size={14}/></span></div></section>
 <section id="work" className="section work"><div className="section-heading reveal"><span className="eyebrow">01 / EXPERIENCE</span><h2>Where I’ve been<br/><span>making an impact.</span></h2></div><article className="experience reveal"><span className="experience-number">01</span><div><span className="eyebrow">MARCH 2024 — PRESENT</span><h3>Konstruksi.AI</h3><p>Frontend Developer</p><div className="experience-note">Current chapter</div></div><span className="status-pill">Current</span></article><article className="experience reveal"><span className="experience-number">02</span><div><span className="eyebrow">JULY 2022 — JULY 2023</span><h3>Kimberly-Clark Softex</h3><p>System Analyst Intern</p><div className="experience-note">A foundation in systems thinking and analysis.</div></div><span className="experience-duration">1 year</span></article></section>
 <section id="skill" className="section skills"><div className="section-heading reveal"><span className="eyebrow">02 / MY TOOLKIT</span><h2>The right tools.<br/><span>A problem-solving mindset.</span></h2></div><div className="skills-grid">{skills.map(({icon:Icon,title,description,tags},i)=><article className="skill-card reveal" key={title}><div className="skill-card-top"><Icon size={24} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{title}</h3><p>{description}</p><div className="tags">{tags.map(tag=><TechBadge key={tag} name={tag}/>)}</div></article>)}</div></section>
 <PersonalProjects/>
 <section id="contact" className="section contact"><div className="contact-intro reveal"><span className="eyebrow">04 / LET’S CONNECT</span><h2>Something in mind?<br/>Let’s make it <em>happen.</em></h2><p>Have a project to build or a remote role to fill? I’d love to hear about it.</p><div className="contact-options"><span>Freelance projects</span><span>Full-time · Fully remote</span></div><a className="email-link" href={`mailto:${recipient}`}><Mail size={17}/><span>{recipient}</span></a><p className="contact-note">Good things start with a conversation.</p></div>
 <form className="contact-form reveal" onSubmit={submit}><div className="form-title"><span>Tell me about your opportunity</span><ArrowUpRight size={22}/></div><div className="form-row"><div className="field"><Label htmlFor="name">Your name *</Label><Input id="name" name="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={100} autoComplete="name" placeholder="How should I call you?" disabled={sending}/></div><div className="field"><Label htmlFor="email">Email address *</Label><Input id="email" name="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254} autoComplete="email" placeholder="you@company.com" disabled={sending}/></div></div>
 <div className="field"><Label htmlFor="inquiry">I’m reaching out about</Label><Select value={kind} onValueChange={value=>{setKind(value as Inquiry);setFeedback(null)}} disabled={sending}><SelectTrigger id="inquiry" className="inquiry-select"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(templates).map(([key,value])=><SelectItem key={key} value={key}>{value.label}</SelectItem>)}</SelectContent></Select></div>
 <div className="field"><Label htmlFor="subject">Subject *</Label><Input id="subject" name="subject" value={draft.subject} onChange={e=>changeDraft("subject",e.target.value)} required maxLength={160} disabled={sending}/></div><div className="field"><div className="message-label"><Label htmlFor="message">Your message *</Label><span>EDITABLE TEMPLATE</span></div><Textarea id="message" name="message" aria-describedby="message-hint" value={draft.message} onChange={e=>changeDraft("message",e.target.value)} required minLength={20} maxLength={5000} rows={9} disabled={sending}/><p id="message-hint" className="field-hint">A starting point, in your own words. Edit the template before sending.</p></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this field empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>
 <Button className="send-button" type="submit" disabled={sending}>{sending?<><LoaderCircle className="spin"/>Sending…</>:<>Send message <Send size={16}/></>}</Button>{feedback&&<div className={`form-feedback ${feedback.type}`} role={feedback.type==="error"?"alert":"status"}>{feedback.message}</div>}<div className="form-footer"><span>Sent securely via FormSubmit.</span><a href={mailto}>Use your email app <ArrowUpRight size={13}/></a></div></form></section></main>
 <footer className="footer"><a className="wordmark" href="#home">clrshna<span aria-hidden="true">.</span></a><span>© {new Date().getFullYear()} Vincentius Clarishna</span><a href="#home" className="back-top">Back to top <ArrowUp size={15}/></a></footer></>;
}
